language: go

go:
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.9
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - 1.9.4
  - 1.10
  - 1.10.1
  - tip

sudo: false

go_import_path: github.com/novln/soba

script:
  - scripts/test
  - scripts/lint
  - scripts/coverage --analyze

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
