version: 2

jobs:
  build:
    machine:
      image: circleci/classic:edge
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Checkout submodules
          command: |
            git submodule sync
            git submodule update --init

      - run:
          name: Run tests
          command: scripts/go-wrapper scripts/test

      - run:
          name: Run linters
          command: scripts/go-wrapper scripts/lint
