#!/bin/bash

set -eo pipefail

SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
cd "${SOURCE_DIRECTORY}/.."


do_analyze() {

    mkdir -p testdata
    go test -covermode=count -coverprofile=testdata/coverage.out .

}

do_view() {

    go tool cover -html=testdata/coverage.out

}


case "$1" in
    --view)
        do_view
    ;;
    --analyze)
        do_analyze
    ;;
    *)
        do_analyze
        do_view
    ;;
esac
exit 0
